import type { Metadata } from 'next'
import { GeistSans } from 'geist/font'
import './globals.css'
import { ModalProvider } from '@/providers/ModalProvider'
import { AuthModal } from '@/components/AuthModal/AuthModal'
import { ToasterProvider } from '@/providers/ToasterProvider'
import { SupabaseProvider } from '@/providers/SupabaseProvider'
import { UserProvider } from '@/providers/UserProvider'
import { UserContextProvider } from '@/hooks/useUser'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <ToasterProvider />
        <SupabaseProvider>
          <UserContextProvider>
            <UserProvider>
              <ModalProvider />
              <AuthModal />
              {children}
            </UserProvider>
          </UserContextProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
