import type { Metadata } from 'next'
import { GeistSans } from 'geist/font'
import './globals.css'
import { SupabaseProvider } from '@/providers/SupabaseProvider'
import { UserProvider } from '@/providers/UserProvider'
import { ModalProvider } from '@/providers/ModalProvider'
import { AuthModal } from '@/components/AuthModal'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
            <AuthModal />
            {children}
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
